"""initial schema

Revision ID: a9ecf7a576e8
Revises: 
Create Date: 2026-08-01 20:13:37.203683
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'a9ecf7a576e8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Trigram matching is what makes `name ILIKE '%query%'` index-backed instead
    # of a sequential scan. Must exist before the index below is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('encryption_salt', sa.LargeBinary(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('github_id', name=op.f('uq_users_github_id')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    op.create_table('folders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_folders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders')),
    sa.UniqueConstraint('user_id', 'parent_id', 'name', name='uq_folders_user_id_parent_id_name')
    )
    op.create_index('ix_folders_user_id_parent_id', 'folders', ['user_id', 'parent_id'], unique=False)
    op.create_index('ix_folders_user_id_path', 'folders', ['user_id', 'path'], unique=False)
    op.create_index('ix_folders_user_id_updated_at', 'folders', ['user_id', 'updated_at'], unique=False)
    op.create_index('uq_folders_user_id_name_root', 'folders', ['user_id', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_refresh_tokens_jti')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_user_id_family_id', 'refresh_tokens', ['user_id', 'family_id'], unique=False)
    op.create_table('sync_tombstones',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sync_tombstones_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_tombstones'))
    )
    op.create_index('ix_sync_tombstones_entity_id', 'sync_tombstones', ['entity_id'], unique=False)
    op.create_index('ix_sync_tombstones_user_id_deleted_at', 'sync_tombstones', ['user_id', 'deleted_at'], unique=False)
    op.create_table('user_telegram_configs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bot_token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('bot_token_hint', sa.String(length=8), nullable=True),
    sa.Column('bot_username', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_telegram_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_telegram_configs')),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_user_telegram_configs_user_id_channel_id')
    )
    op.create_index('ix_user_telegram_configs_user_id_is_active', 'user_telegram_configs', ['user_id', 'is_active'], unique=False)
    op.create_table('files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_provider', sa.String(length=32), server_default='telegram', nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('telegram_file_unique_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('is_chunked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('chunk_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_chunked AND chunk_count > 0) OR (NOT is_chunked AND chunk_count = 0)', name=op.f('ck_files_chunk_count_matches_is_chunked')),
    sa.CheckConstraint('(is_deleted AND deleted_at IS NOT NULL) OR (NOT is_deleted AND deleted_at IS NULL)', name=op.f('ck_files_deleted_at_matches_is_deleted')),
    sa.CheckConstraint('size >= 0', name=op.f('ck_files_size_non_negative')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_files_folder_id_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index('ix_files_deleted_at', 'files', ['deleted_at'], unique=False, postgresql_where=sa.text('is_deleted'))
    op.create_index('ix_files_telegram_channel_id_telegram_message_id', 'files', ['telegram_channel_id', 'telegram_message_id'], unique=False, postgresql_where=sa.text('telegram_message_id IS NOT NULL'))
    op.create_index('ix_files_user_id_folder_id_is_deleted_created_at', 'files', ['user_id', 'folder_id', 'is_deleted', 'created_at'], unique=False)
    op.create_index('ix_files_user_id_sha256', 'files', ['user_id', 'sha256'], unique=False)
    op.create_index('ix_files_user_id_size', 'files', ['user_id', 'size'], unique=False)
    op.create_index('ix_files_user_id_updated_at', 'files', ['user_id', 'updated_at'], unique=False)

    # Raw DDL: Alembic's index API cannot express the `gin_trgm_ops` operator
    # class. `alembic/env.py` excludes this index from autogenerate so it is not
    # proposed for deletion on every future revision.
    op.execute(
        "CREATE INDEX ix_files_name_trgm ON files USING gin (name gin_trgm_ops)"
    )

    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_activity_logs_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index('ix_activity_logs_file_id', 'activity_logs', ['file_id'], unique=False)
    op.create_index('ix_activity_logs_user_id_created_at', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('file_chunks',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('offset', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=True),
    sa.Column('telegram_file_unique_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_file_chunks_chunk_index_non_negative')),
    sa.CheckConstraint('size > 0', name=op.f('ck_file_chunks_chunk_size_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_chunks_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_chunks')),
    sa.UniqueConstraint('file_id', 'chunk_index', name='uq_file_chunks_file_id_chunk_index')
    )
    op.create_index('ix_file_chunks_file_id_chunk_index', 'file_chunks', ['file_id', 'chunk_index'], unique=False)
    op.create_table('file_tags',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_tags_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', 'tag', name=op.f('pk_file_tags'))
    )
    op.create_index('ix_file_tags_tag', 'file_tags', ['tag'], unique=False)
    op.create_table('shared_links',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('download_count >= 0', name=op.f('ck_shared_links_download_count_non_negative')),
    sa.CheckConstraint('max_downloads IS NULL OR max_downloads > 0', name=op.f('ck_shared_links_max_downloads_positive')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_shared_links_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shared_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_links')),
    sa.UniqueConstraint('token', name=op.f('uq_shared_links_token'))
    )
    op.create_index('ix_shared_links_file_id', 'shared_links', ['file_id'], unique=False)
    op.create_index('ix_shared_links_user_id', 'shared_links', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_files_name_trgm")
    # The pg_trgm extension is deliberately left installed: it is database-wide
    # and something else may depend on it.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shared_links_user_id', table_name='shared_links')
    op.drop_index('ix_shared_links_file_id', table_name='shared_links')
    op.drop_table('shared_links')
    op.drop_index('ix_file_tags_tag', table_name='file_tags')
    op.drop_table('file_tags')
    op.drop_index('ix_file_chunks_file_id_chunk_index', table_name='file_chunks')
    op.drop_table('file_chunks')
    op.drop_index('ix_activity_logs_user_id_created_at', table_name='activity_logs')
    op.drop_index('ix_activity_logs_file_id', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_files_user_id_updated_at', table_name='files')
    op.drop_index('ix_files_user_id_size', table_name='files')
    op.drop_index('ix_files_user_id_sha256', table_name='files')
    op.drop_index('ix_files_user_id_folder_id_is_deleted_created_at', table_name='files')
    op.drop_index('ix_files_telegram_channel_id_telegram_message_id', table_name='files', postgresql_where=sa.text('telegram_message_id IS NOT NULL'))
    op.drop_index('ix_files_deleted_at', table_name='files', postgresql_where=sa.text('is_deleted'))
    op.drop_table('files')
    op.drop_index('ix_user_telegram_configs_user_id_is_active', table_name='user_telegram_configs')
    op.drop_table('user_telegram_configs')
    op.drop_index('ix_sync_tombstones_user_id_deleted_at', table_name='sync_tombstones')
    op.drop_index('ix_sync_tombstones_entity_id', table_name='sync_tombstones')
    op.drop_table('sync_tombstones')
    op.drop_index('ix_refresh_tokens_user_id_family_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_folders_user_id_name_root', table_name='folders', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index('ix_folders_user_id_updated_at', table_name='folders')
    op.drop_index('ix_folders_user_id_path', table_name='folders')
    op.drop_index('ix_folders_user_id_parent_id', table_name='folders')
    op.drop_table('folders')
    op.drop_table('users')
    # ### end Alembic commands ###
